import asyncio
from mcp_client_server.mcp_client import mcpclient
exPrompt= """I require a detailed analysis of the system’s vibration monitoring capabilities to establish a robust threshold frequency for leak detection in pipelines. Specifically, I need to understand the following:

Given the flow control diagram (Figure 2.5) which depicts the system architecture, I require a comprehensive breakdown of the frequency analysis module.  This module, as indicated by 2.7.1 Frequency Analysis, appears to utilize a mathematical model to process the raw vibration recordings.  Please provide the specific mathematical algorithms employed, including any relevant equations or formulas used for frequency domain analysis.  Furthermore, detail the input variables (e.g., sampling rate, sensor type, signal conditioning) and the output variables (e.g., frequency spectrum, amplitude, phase) generated by this module.  I also need to know the sampling rate, the type of sensors being utilized, and the signal conditioning employed.

I need to understand the flow control diagram’s (Figure 2.5) interaction with the raw vibration recordings.  Identify which components within the system are responsible for acquiring, processing, and ultimately generating the frequency data used for leak detection.  Specifically, I require details on the data logging frequency, the method used to transform the vibration data into the frequency domain, and the parameters used to define the frequency range of analysis.  What type of sensors are being used to collect the vibration data? 

I require a precise definition of the ‘threshold frequency’ being targeted.  Does the system include any pre-defined thresholds, or is it designed to learn or adapt a threshold based on the specific pipeline characteristics and vibration patterns?  Are there any adjustable parameters related to the frequency threshold, and if so, what are their ranges and impact on the leak detection performance?  What are the system’s assumptions regarding the correlation between fluid leaks and specific frequency components in the vibration signal?"""

connectlogical = mcpclient("logical")
connectStructural = mcpclient("structural")
connectTheoritcal = mcpclient("Theoritcal")
    
async def connect():    
    try:
        await asyncio.gather(
            connectlogical.connect_to_server("mcp_client_server/logicalserver.py"),
            connectStructural.connect_to_server("mcp_client_server/Structuralserver.py"),
            connectTheoritcal.connect_to_server("mcp_client_server/theoriticalserver.py")
        )
    except Exception as e:
        print("something went wrong")
    
    print("calling tools")
    result = None
    try:
       print("entering async gather for servers")
       result =  await asyncio.gather(
                    connectTheoritcal.call_analysis("theoriticalServer", {"prompt": exPrompt}),
                    connectStructural.call_analysis("structuralServer", {"prompt": exPrompt}),
                    connectlogical.call_analysis("logicalServer", {"prompt": exPrompt})
                     )
    except Exception as e:
        print(f'Something went wrong: Error Details : {e}')
    finally:
            await asyncio.gather(
                connectlogical.close_async_context(),
                connectStructural.close_async_context(),
                connectTheoritcal.close_async_context(),
                return_exceptions= True
            )

    if result is None:
        print("No result returned")

if __name__ == "__main__":
  result = asyncio.run(connect())
  print(result)
    